Predicting whether customer is a Wholesaler or Retailer

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

Data gathering and cleaning

In [3]:
df = pd.read_csv("DSA_ecommerce_bigdata.csv")

df.isnull().sum()

df.duplicated().sum()

df.describe()

             Sales       Profit
count   200.000000   200.000000
mean   2567.190000   456.367350
std    1528.736925   346.853151
min      56.000000     5.130000
25%    1200.500000   173.967500
50%    2428.000000   379.330000
75%    4052.000000   675.000000
max    4998.000000  1377.040000

Encoding

In [4]:
encoded_df = pd.get_dummies(df,columns=['Region','ProductCategory'])
encoded_df

,TransactionID,Date,CustomerType,Sales,Profit,Region_Central,Region_Eastern,Region_Northern,Region_Western,ProductCategory_Beverages,ProductCategory_Clothing,ProductCategory_Electronics,ProductCategory_Food,ProductCategory_Household Products
0,TX0001,2026-06-16,Wholesale,4924,359.44,False,True,False,False,False,False,True,False,False
1,TX0002,2026-02-12,Retail,3283,944.32,True,False,False,False,False,False,True,False,False
2,TX0003,2026-03-01,Online,4049,967.10,False,False,True,False,False,False,False,True,False
3,TX0004,2026-06-03,Online,4331,434.57,False,False,False,True,False,False,False,False,True
4,TX0005,2026-01-21,Retail,3283,340.48,False,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,TX0196,2026-05-17,Online,4360,361.90,False,True,False,False,False,False,False,False,True
196,TX0197,2026-05-23,Wholesale,2138,143.04,False,True,False,False,False,True,False,False,False
197,TX0198,2026-01-12,Online,3530,744.03,False,False,True,False,False,True,False,False,False
198,TX0199,2026-06-14,Retail,3470,792.78,False,False,False,True,False,False,False,False,True
199,TX0200,2026-03-18,Retail,4063,1013.02,False,False,False,True,True,False,False,False,False

splitting data

In [5]:
y = encoded_df['CustomerType']
y
X = encoded_df.drop(columns=['CustomerType','TransactionID','Date'])
#X


X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=20)

Model selection and training

In [7]:
log_reg = LogisticRegression(random_state=20,max_iter=5000)
dec_tree = DecisionTreeClassifier(random_state=20)
rand_forest = RandomForestClassifier(random_state=20)

models = {
    "Logistics Model":log_reg,
    "Decision Tree":dec_tree,
    "Random Forest":rand_forest
}


for name,model in models.items():
    model.fit(X_train,y_train)
    accuracy = model.score(X_test,y_test)
    y_pred = model.predict(X_test)
    
    print(f"model: {name}\nAccuracy Score: {accuracy}")
    print("---------Classification Report ------------")
    print(classification_report(y_test,y_pred))

model: Logistics Model
Accuracy Score: 0.375
---------Classification Report ------------
              precision    recall  f1-score   support

      Online       0.75      0.19      0.30        16
      Retail       0.12      0.10      0.11        10
   Wholesale       0.39      0.79      0.52        14

    accuracy                           0.38        40
   macro avg       0.42      0.36      0.31        40
weighted avg       0.47      0.38      0.33        40

model: Decision Tree
Accuracy Score: 0.35
---------Classification Report ------------
              precision    recall  f1-score   support

      Online       0.55      0.38      0.44        16
      Retail       0.21      0.30      0.25        10
   Wholesale       0.33      0.36      0.34        14

    accuracy                           0.35        40
   macro avg       0.36      0.34      0.35        40
weighted avg       0.39      0.35      0.36        40

model: Random Forest
Accuracy Score: 0.3
---------Classification Report ------------
              precision    recall  f1-score   support

      Online       0.56      0.31      0.40        16
      Retail       0.11      0.10      0.11        10
   Wholesale       0.27      0.43      0.33        14

    accuracy                           0.30        40
   macro avg       0.31      0.28      0.28        40
weighted avg       0.35      0.30      0.30        40